### ISSUE TITLE
Feature Request - export libraries as CSV (but not actually comma delimited)

### ISSUE THREAD

**Issue by jcdick1** [LSchallot/JellyRoller#6]
The Reports plugin has a lot of issues that would require a complete rewrite of the plugin.  The CSV exporter uses an actual comma as a delimiter, but a comma is also hard-coded in JF as the separator between things like genre when an item is considered multiple genres.  And so the columns get all messed up.  The Excel exporter is only a web scraper, and so it can only export as many items as there are on the page at the time.  If you have a lot of items (I have 700+ movies), it kills the plugin trying to build a page to list them.

If you could add an exporter that can then be brought into a spreadsheet for library management, that'd be great.  

Something like "jellyroller export-library" and have it dump out a CSV per library.

**Comment by LSchallot** [comment]
Thanks for submitting a feature request.
I will look into the functionality of the various plugins and see what can be done via the API.  I imagine I should be able to at least get some sort of basic export that can be used in Excel.  I may also need some assistance with testing for a larger library.

**Comment by LSchallot** [comment]
CLI table of activity is now available in the branch associated with this issue.  I will work on csv export of the activity next.  Trying to mimic the reports plugin output of media will be a pain as the JSON objects that are returned are messy (that is being nice).

If a test version is requested, I will gladly build and attach a binary to this issue.

**Comment by LSchallot** [comment]
The activities information can now be exported as a csv.  This should complete the recreation of the activity piece of the Reports plugin.  Work on library information will be done as I have time.

**Comment by LSchallot** [comment]
@jcdick1 
I have finally been able to put some effort into this request.  I have a working exporter for Movies at this point and am currently working on adding additional items.
I currently have just over 250 movies available on my server which is hosted on an RPi 2 so hopefully my results are on the slower end of the spectrum.  Executing a movie export via cargo run runs in 4.91 seconds at the current time.  Since you mentioned you have 700+ items, would you be willing to execute a test build so I can get some metrics on larger libraries?
